# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://zhangs06.github.io' # the base hostname & protocol for your site

title: 'Shuo Zhang'
author: 'Shuo Zhang'

languages: [ 'en', 'de' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '34398828@N04'
flickr_api_key: 780efdea9f297a0a24a84acddc8c0b93
flickr_api_secret: 4d2e3a2cb62bdd71

default_header_img_dimensions: 'width="392" height="549"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Daniel Limberger, a Berlin based Graphics Systems Engineer, Researcher, and Entrepreneur. It enlists his publications, projects, talks, teachings, and contact information.'
  - scope:
      path: 'de'
    values:
      lang: de
      description: 'Persönliche Webseite von Daniel Limberger, Ingeniuer für grafische System, Forscher und Unternehmer. Die Webseite listet Veröffentlichungen, Projekte, Vorträge, Lehrtätigkeiten und Kontaktdaten.'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed

