# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://zhangs06.github.io' # the base hostname & protocol for your site

title: 'Shuo Zhang'
author: 'Shuo Zhang'

languages: [ 'en', 'cn' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: '34398828@N04'
flickr_api_key: 780efdea9f297a0a24a84acddc8c0b93
flickr_api_secret: 4d2e3a2cb62bdd71

default_header_img_dimensions: 'width="392" height="549"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Shuo Zhang, a Research Geologist in Aramco Global Research Centers - Houston. It enlists his publications, conferences, teachings, and contact information.'
  - scope:
      path: 'cn'
    values:
      lang: cn
      description: '沙特阿美国家石油公司休斯敦研究中心地质研究员张硕的个人网站.包括他发表的文章，会议，授课，以及联系信息'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:
  - 'README.md'
  - 'util'
  - 'config'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'Rakefile'
  - 'vendor'
  - 'config.ru'
  - 'unicorn.rb'
  - 'fabfile.py'
  - 'node_modules'
  - 'bower_components'
  - 'package.json'
  - 'bower.json'
  - 'Gruntfile.js'
  - 'assets/_css'
  - 'assets/_less'
  - 'assets/_img'
  - '.travis.yml'
keep_files:
  - '.git'
  - '.svn'
gems:        []
timezone:    nil
encoding:    utf-8

future:      true
show_drafts: false
limit_posts: 0
highlighter: pygments

relative_permalinks: true
permalink: "/posts/:title"

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions:
    - 'smart'

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
